// Auto-generated by scripts/generate-build-info.sh — do not edit by hand.
// Regenerated on every Xcode / xcodebuild compile.
import AppKit
import Foundation

enum BuildInfo {
    /// Human-readable local time when this binary was compiled.
    static let timestamp = "2026-08-08 09:03:26 PDT"

    /// Compact stamp for quick comparison (e.g. 20260806.213206).
    static let stamp = "20260808.090326"

    /// Machine-sortable build instant.
    static let isoTimestamp = "2026-08-08T09:03:26-0700"

    static var marketingVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "—"
    }

    static var buildNumber: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "—"
    }

    static var configuration: String {
        #if DEBUG
        "Debug"
        #else
        "Release"
        #endif
    }

    /// One-line identity for logs and the Build Info panel.
    static var summary: String {
        "Markdowner \(marketingVersion) (\(buildNumber)) · \(configuration) · built \(timestamp)"
    }

    static var detailText: String {
        """
        Version: \(marketingVersion)
        Build: \(buildNumber)
        Configuration: \(configuration)
        Built: \(timestamp)
        Stamp: \(stamp)

        Bundle:
        \(Bundle.main.bundlePath)
        """
    }

    @MainActor
    static func presentPanel() {
        let alert = NSAlert()
        alert.messageText = "Markdowner Build Info"
        alert.informativeText = detailText
        alert.alertStyle = .informational
        alert.addButton(withTitle: "OK")
        alert.addButton(withTitle: "Copy")
        let response = alert.runModal()
        if response == .alertSecondButtonReturn {
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(detailText, forType: .string)
        }
    }
}
