#!/usr/bin/env bash
# Writes Markdowner/BuildInfo.swift with the current local build date/time.
# Invoked as an Xcode "Run Script" phase before Compile Sources so every binary
# carries a unique stamp you can compare from Help → Build Info…
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/Markdowner/BuildInfo.swift"

# Prefer the project root from Xcode when available.
if [[ -n "${SRCROOT:-}" ]]; then
  OUT="${SRCROOT}/Markdowner/BuildInfo.swift"
  ROOT="${SRCROOT}"
fi

TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"
STAMP="$(date '+%Y%m%d.%H%M%S')"
# ISO-ish for machine compare
ISO="$(date '+%Y-%m-%dT%H:%M:%S%z')"

# Escape for embedding in a Swift string literal
escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

TS_ESC="$(escape "$TS")"
STAMP_ESC="$(escape "$STAMP")"
ISO_ESC="$(escape "$ISO")"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit by hand.
// Regenerated on every Xcode / xcodebuild compile.
import AppKit
import Foundation

enum BuildInfo {
    /// Human-readable local time when this binary was compiled.
    static let timestamp = "${TS_ESC}"

    /// Compact stamp for quick comparison (e.g. 20260806.213206).
    static let stamp = "${STAMP_ESC}"

    /// Machine-sortable build instant.
    static let isoTimestamp = "${ISO_ESC}"

    static var marketingVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "—"
    }

    static var buildNumber: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "—"
    }

    static var configuration: String {
        #if DEBUG
        "Debug"
        #else
        "Release"
        #endif
    }

    /// One-line identity for logs and the Build Info panel.
    static var summary: String {
        "Markdowner \\(marketingVersion) (\\(buildNumber)) · \\(configuration) · built \\(timestamp)"
    }

    static var detailText: String {
        """
        Version: \\(marketingVersion)
        Build: \\(buildNumber)
        Configuration: \\(configuration)
        Built: \\(timestamp)
        Stamp: \\(stamp)

        Bundle:
        \\(Bundle.main.bundlePath)
        """
    }

    @MainActor
    static func presentPanel() {
        let alert = NSAlert()
        alert.messageText = "Markdowner Build Info"
        alert.informativeText = detailText
        alert.alertStyle = .informational
        alert.addButton(withTitle: "OK")
        alert.addButton(withTitle: "Copy")
        let response = alert.runModal()
        if response == .alertSecondButtonReturn {
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(detailText, forType: .string)
        }
    }
}
EOF

echo "note: Generated BuildInfo.swift → ${TS} (${STAMP})"
